('dtformat', '%Y-%m-%d'),
('tmformat' , '%H:%M:%S'),
('sentiment_mean' , 1),
('sentiment_median' , 2),
('datetime' , 3),
('time' , 4),
('open' , 5),
('close' , 6),
('volume' , 7),
('high' , -1),
('low' , 2),
('openinterest' , -1),
('timeframe' , bt.TimeFrame.Minutes),
('compression' , 60)